#     _   _____________ ____  ____  ______    ____  ____  ______
#    / | / / ____/ ___// __ \/ __ \/_  __/   / __ \/ __ \/ ____/
#   /  |/ / /    \__ \/ /_/ / / / / / /_____/ /_/ / /_/ / /
#  / /|  / /___ ___/ / ____/ /_/ / / /_____/ _, _/ ____/ /___
# /_/ |_/\____//____/_/    \____/ /_/     /_/ |_/_/    \____/

# Thank you for using my app!
# Please ensure you've read the documentation in this file and on the Github Page for a quick, comprehensive guide!
# You're on your own soldier, good luck!


[general]
DEBUG = true # Allow debugging logs in I/O
LOGS_ADD_SONG = true # Once updated on RPC, add additional logging to show what song is displaying on RPC.

[socket]
RUNTIME_PATH = "/run/user/1000/ncspot" # Leave this unchanged unless 'ncspot info' says the 'USER_RUNTIME_PATH' is otherwise.

[api]
DISCORD_CLIENT_ID = 1475331730884788379 # Our public, community maintained, client ID, We recommend you leave this alone. If you want to use your own client, read docs/CUSTOM_CLIENT.md

[format]
DISPLAY_CLIENT = true # Display if we are using ncspot to play music, Will be "Spotify" if false.
DISPLAY_PLAYER_ICON = true # Display the small player icon to the bottom right of Album Art
DISPLAY_PROGRESS = true # Display song progress in RPC. Eg 1:15 -> 3:41
